import type { VariantManifest } from "@/features/variants/types";

export const variantManifests: VariantManifest[] = [
  {
    id: "deep-immersion",
    family: "dark_atmosphere",
    label: "Deep Immersion",
    northStar: "The Abyss Reader",
    summary: "Primary deep-abyss portfolio with blue accent, sharp masonry, and Russian collector-facing copy.",
    supportedRoutes: ["home", "gallery", "detail", "about", "contacts"],
    pageTemplates: {
      home: "home",
      gallery: "gallery",
      detail: "artwork_detail",
      about: "about",
      contacts: "contact",
    },
    textSource: [
      "ref/template/stitch_dark_atmosphere_portfolio_prd/home/code.html",
      "ref/template/stitch_dark_atmosphere_portfolio_prd/gallery/code.html",
      "ref/template/stitch_dark_atmosphere_portfolio_prd/artwork_detail/code.html",
      "ref/template/stitch_dark_atmosphere_portfolio_prd/about/code.html",
      "ref/template/stitch_dark_atmosphere_portfolio_prd/contact/code.html",
    ],
    designInvariants: [
      "Inter hero and navigation with Cabinet Grotesk accents on utility pages",
      "Deep abyss background with crisp blue primary accent",
      "Sharp 0px geometry and simple structural lines",
      "Masonry archive with soft hover glows instead of card chrome",
      "Russian copy and collector-facing editorial restraint",
    ],
    doNotDilute: [
      "Do not merge this into cold-mist fog or etheric glow logic",
      "Do not replace the blue accent with neutral gray or copper warmth",
      "Do not soften the masonry and split hero into generic cards",
    ],
    classes: {
      body: "bg-[#07090F] text-[#F1F4F9]",
      surface: "bg-[#12151E] text-[#F1F4F9]",
      card: "bg-[#12151E] text-[#F1F4F9]",
      accent: "bg-[#1378ec] text-white",
      subtle: "text-[#5A657A]",
      hero: "bg-[radial-gradient(circle_at_70%_50%,_rgba(19,120,236,0.18),_transparent_45%),linear-gradient(180deg,_#07090F,_#07090F)]",
      pill: "rounded-none",
      artworkFrame: "rounded-none",
    },
  },
  {
    id: "cold-mist",
    family: "dark_atmosphere",
    label: "Cold Mist",
    northStar: "The Ethereal Monolith",
    summary: "Clinical editorial darkness, tonal layering, no-line containment, icy restraint.",
    supportedRoutes: ["home", "gallery", "detail", "about", "contacts"],
    pageTemplates: {
      home: "home_mist",
      gallery: "gallery_mist",
      detail: "detail_mist",
      about: "about",
      contacts: "contact",
    },
    textSource: [
      "ref/template/stitch_dark_atmosphere_portfolio_prd/cold_mist/DESIGN.md",
      "ref/template/stitch_dark_atmosphere_portfolio_prd/home_mist/code.html",
      "ref/template/stitch_dark_atmosphere_portfolio_prd/gallery_mist/code.html",
      "ref/template/stitch_dark_atmosphere_portfolio_prd/detail_mist/code.html",
    ],
    designInvariants: [
      "0px corners only",
      "No visible structural lines",
      "Slate and charcoal tonal depth",
      "Tight editorial typography blocks",
      "Cold fog and frosted surfaces over hard shadows",
    ],
    doNotDilute: [
      "Do not introduce rounded cards or pills",
      "Do not brighten the palette into warm copper",
      "Do not replace tonal separation with borders",
    ],
    classes: {
      body: "bg-[#0b1017] text-[#e1e4fb]",
      surface: "bg-[#101723] text-[#e1e4fb]",
      card: "bg-[#121a25] text-[#e1e4fb]",
      accent: "bg-[#bfc7cf] text-[#0b1017]",
      subtle: "text-[#9facc1]",
      hero: "bg-[radial-gradient(circle_at_top,_rgba(219,224,234,0.12),_transparent_38%),linear-gradient(135deg,_#0a0e14,_#111925_55%,_#1a2637)]",
      pill: "rounded-none",
      artworkFrame: "rounded-none",
    },
  },
  {
    id: "copper-glow",
    family: "dark_atmosphere",
    label: "Copper Glow",
    northStar: "The Cinematic Alchemist",
    summary: "Abyssal gallery with copper light, sharp brutalist edges, cinematic warmth.",
    supportedRoutes: ["home", "gallery", "detail", "about", "contacts"],
    pageTemplates: {
      home: "home_copper",
      gallery: "gallery_copper",
      detail: "detail_copper",
      about: "about",
      contacts: "contact",
    },
    textSource: [
      "ref/template/stitch_dark_atmosphere_portfolio_prd/copper_glow/DESIGN.md",
      "ref/template/dark_atmosphere_portfolio_prd.html",
      "ref/template/stitch_dark_atmosphere_portfolio_prd/home_copper/code.html",
      "ref/template/stitch_dark_atmosphere_portfolio_prd/gallery_copper/code.html",
    ],
    designInvariants: [
      "0px corners only",
      "Copper radial glow instead of flat dark mode",
      "Cabinet Grotesk / Satoshi editorial pairing",
      "No-line sectioning with abyss surfaces",
      "Warm spotlight logic around artworks",
    ],
    doNotDilute: [
      "Do not soften edges with rounded geometry",
      "Do not swap copper lighting for neutral grayscale",
      "Do not convert editorial asymmetry into generic centered layouts",
    ],
    classes: {
      body: "bg-[#11131a] text-[#f1f4f9]",
      surface: "bg-[#191b22] text-[#f1f4f9]",
      card: "bg-[#282a31] text-[#f1f4f9]",
      accent: "bg-[#e8be9f] text-[#442b14]",
      subtle: "text-[#b8c2d1]",
      hero: "bg-[radial-gradient(circle_at_top_right,_rgba(140,106,79,0.28),_transparent_42%),linear-gradient(135deg,_#11131a,_#161922_55%,_#231e1a)]",
      pill: "rounded-none",
      artworkFrame: "rounded-none",
    },
  },
  {
    id: "etheric-pulse",
    family: "dark_atmosphere",
    label: "Etheric Pulse",
    northStar: "The Ethereal Curator",
    summary: "Breathing dark gallery with energy glows, glassmorphism, and mystical fluid emphasis.",
    supportedRoutes: ["home", "gallery", "detail", "about", "contacts"],
    pageTemplates: {
      home: "home_energy_flows",
      gallery: "gallery_energy_flows",
      detail: "artwork_detail",
      about: "about_energy_flows",
      contacts: "contact",
    },
    textSource: [
      "ref/template/stitch_dark_atmosphere_portfolio_prd/etheric_pulse/DESIGN.md",
      "ref/template/stitch_dark_atmosphere_portfolio_prd/home_energy_flows/code.html",
      "ref/template/stitch_dark_atmosphere_portfolio_prd/gallery_energy_flows/code.html",
      "ref/template/stitch_dark_atmosphere_portfolio_prd/about_energy_flows/code.html",
    ],
    designInvariants: [
      "Deep void base with violet, teal, and rose energy accents",
      "Glassmorphism overlays and organic glow zones",
      "Rounded interactive elements and breathing motion",
      "No hard borders for sectioning",
      "Interface must recede behind artwork energy",
    ],
    doNotDilute: [
      "Do not flatten this into rigid editorial brutalism",
      "Do not replace glow-led separation with static cards",
      "Do not remove rounded pulses and fluid softness",
    ],
    classes: {
      body: "bg-[#0c0e17] text-[#e1e4fb]",
      surface: "bg-[rgba(39,43,62,0.7)] text-[#e1e4fb] backdrop-blur-xl",
      card: "bg-[rgba(31,35,50,0.82)] text-[#e1e4fb] shadow-[0_24px_60px_rgba(168,148,255,0.12)]",
      accent: "bg-[#a894ff] text-[#0c0e17]",
      subtle: "text-[#b9c0d7]",
      hero: "bg-[radial-gradient(circle_at_top_left,_rgba(168,148,255,0.25),_transparent_38%),radial-gradient(circle_at_bottom_right,_rgba(130,211,220,0.22),_transparent_32%),linear-gradient(135deg,_#0c0e17,_#121628_55%,_#191e35)]",
      pill: "rounded-full",
      artworkFrame: "rounded-[2rem]",
    },
  },
  {
    id: "mint-rose",
    family: "organic_flow",
    label: "Mint Rose",
    northStar: "Cozy fluid immersion",
    summary: "Powdery rose, mint glass surfaces, soft liquid forms, delicate editorial warmth.",
    supportedRoutes: ["home", "gallery", "detail", "contacts"],
    pageTemplates: {
      home: "home_1",
      gallery: "gallery_1",
      detail: "artwork_detail_1",
      contacts: "contact",
    },
    textSource: [
      "ref/template/organic_flow_mint_rose_prd.html",
      "ref/template/stitch_organic_flow_prd/home_1/code.html",
      "ref/template/stitch_organic_flow_prd/gallery_1/code.html",
      "ref/template/stitch_organic_flow_prd/artwork_detail_1/code.html",
    ],
    designInvariants: [
      "Fluid blob masking and watercolor softness",
      "Cormorant Garamond with lightweight sans body",
      "Glassmorphism over powdery rose background",
      "No sharp geometry in images or buttons",
      "Tender, soothing collector journey",
    ],
    doNotDilute: [
      "Do not introduce sharp brutalist rectangles",
      "Do not mute mint-and-rose emotional contrast",
      "Do not replace organic masks with plain rounded rectangles",
    ],
    classes: {
      body: "bg-[#f9ecec] text-[#4a403a]",
      surface: "bg-[rgba(255,245,245,0.7)] text-[#4a403a] backdrop-blur-xl",
      card: "bg-[rgba(255,245,245,0.82)] text-[#4a403a] shadow-[0_20px_40px_rgba(74,64,58,0.08)]",
      accent: "bg-[#98d8c8] text-[#30423b]",
      subtle: "text-[#bcaaa4]",
      hero: "bg-[radial-gradient(circle_at_top_left,_rgba(152,216,200,0.28),_transparent_34%),linear-gradient(135deg,_#f9ecec,_#fff5f5_58%,_#f2efea)]",
      pill: "rounded-full",
      artworkFrame: "rounded-[40%_60%_70%_30%/40%_50%_60%_50%]",
    },
  },
  {
    id: "olive-cream",
    family: "organic_flow",
    label: "Olive Cream",
    northStar: "Earthy tactile catalog",
    summary: "Rich cream canvas, olive editorial gravity, literary tone, tactile softness.",
    supportedRoutes: ["home", "gallery", "detail", "contacts"],
    pageTemplates: {
      home: "home_2",
      gallery: "gallery_2",
      detail: "artwork_detail_2",
      contacts: "contact",
    },
    textSource: [
      "ref/template/organic_flow_olive_cream_prd.html",
      "ref/template/stitch_organic_flow_prd/home_2/code.html",
      "ref/template/stitch_organic_flow_prd/gallery_2/code.html",
      "ref/template/stitch_organic_flow_prd/artwork_detail_2/code.html",
    ],
    designInvariants: [
      "Earthy cream and olive palette with tactile warmth",
      "Cormorant Garamond and Lora literary pairing",
      "Organic masks but heavier editorial density than Mint Rose",
      "Soft olive-tinted shadows",
      "Collector path focused on artwork detail and inquiry",
    ],
    doNotDilute: [
      "Do not brighten this into pastel mint lightness",
      "Do not replace literary serif body with slick tech UI rhythm",
      "Do not flatten tactile surfaces into neutral white cards",
    ],
    classes: {
      body: "bg-[#f2efe9] text-[#2c2e27]",
      surface: "bg-[#e8e3d9] text-[#2c2e27]",
      card: "bg-[#e8e3d9] text-[#2c2e27] shadow-[0_20px_40px_-10px_rgba(90,107,71,0.08)]",
      accent: "bg-[#5a6b47] text-[#f2efe9]",
      subtle: "text-[#8f9584]",
      hero: "bg-[radial-gradient(circle_at_top_left,_rgba(125,143,102,0.14),_transparent_36%),linear-gradient(135deg,_#f2efe9,_#ece6da_60%,_#e0d9cb)]",
      pill: "rounded-full",
      artworkFrame: "rounded-[60%_40%_30%_70%/60%_30%_70%_40%]",
    },
  },
  {
    id: "sage-sand",
    family: "organic_flow",
    label: "Sage Sand",
    northStar: "Calm intimate discovery",
    summary: "Warm sand foundation, sage rhythm, soft gallery intimacy, personal narrative flow.",
    supportedRoutes: ["home", "gallery", "detail", "about", "contacts"],
    pageTemplates: {
      home: "home_3",
      gallery: "gallery_index",
      detail: "artwork_detail_2",
      about: "about",
      contacts: "contact",
    },
    textSource: [
      "ref/template/organic_flow_sage_sand_prd.html",
      "ref/template/stitch_organic_flow_prd/home_3/code.html",
      "ref/template/stitch_organic_flow_prd/gallery_index/code.html",
      "ref/template/stitch_organic_flow_prd/about/code.html",
    ],
    designInvariants: [
      "Sage and sand emotional softness",
      "Cormorant with DM Sans for lighter editorial cadence",
      "Soft asymmetric masks and floating cards",
      "Personal narrative and about-page intimacy",
      "Clay hover accents rather than high contrast punch",
    ],
    doNotDilute: [
      "Do not darken it into olive-heavy density",
      "Do not remove personal-story emphasis from About",
      "Do not replace asymmetric softness with strict symmetric grids",
    ],
    classes: {
      body: "bg-[#e8e2d2] text-[#2b3327]",
      surface: "bg-[#f4f0e6] text-[#2b3327]",
      card: "bg-[#f4f0e6] text-[#2b3327] shadow-[0_20px_40px_rgba(43,51,39,0.06)]",
      accent: "bg-[#7d8c74] text-[#f4f0e6]",
      subtle: "text-[#8e9389]",
      hero: "bg-[radial-gradient(circle_at_top_right,_rgba(212,163,115,0.16),_transparent_30%),linear-gradient(135deg,_#e8e2d2,_#f4f0e6_56%,_#e0d8c8)]",
      pill: "rounded-full",
      artworkFrame: "rounded-[40%_60%_70%_30%/40%_50%_60%_50%]",
    },
  },
];

export const defaultVariantId = "cold-mist";

export function isVariantId(value: string) {
  return variantManifests.some((variant) => variant.id === value);
}

export function getVariantManifest(variantId: string) {
  return variantManifests.find((variant) => variant.id === variantId) ?? null;
}
